apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: car-service
  name: car-service
spec:
  ports:
    - name: "4560"
      port: 4560
      targetPort: 4560
  selector:
    io.kompose.service: car-service
