apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: driver-service
  name: driver-service
spec:
  ports:
    - name: "4567"
      port: 4567
      targetPort: 4567
  selector:
    io.kompose.service: driver-service
