apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gateway
  template:
    metadata:
      labels:
        io.kompose.service: gateway
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICE_URL
              value: http://eureka:8761/eureka/
          image: maydek/gateway
          name: gateway
          ports:
            - containerPort: 8088
              protocol: TCP
      restartPolicy: Always
