apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  ports:
    - name: "8088"
      port: 8088
      targetPort: 8088
  selector:
    io.kompose.service: gateway
