apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'car-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['car-service:4560']

      - job_name: 'driver-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['driver-service:4567']

      - job_name: 'passenger-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['passenger-service:4566']

      - job_name: 'ride-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['ride-service:4568']

      - job_name: 'rating-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['rating-service:4569']

      - job_name: 'gateway'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['gateway:8088']
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: prometheus
  name: prometheus-cm0
