apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: rating-service
  name: rating-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rating-service
  template:
    metadata:
      labels:
        io.kompose.service: rating-service
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICE_URL
              value: http://eureka:8761/eureka/
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/ratingdb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          image: maydek/rating-service
          name: rating-service
          ports:
            - containerPort: 4569
              protocol: TCP
      restartPolicy: Always
