apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Windows\system32\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: ride-service
  name: ride-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ride-service
  template:
    metadata:
      labels:
        io.kompose.service: ride-service
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICE_URL
              value: http://eureka:8761/eureka/
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/ridedb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          image: maydek/ride-service
          name: ride-service
          ports:
            - containerPort: 4568
              protocol: TCP
      restartPolicy: Always
