apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ride-service
  name: ride-service
spec:
  ports:
    - name: "4568"
      port: 4568
      targetPort: 4568
  selector:
    io.kompose.service: ride-service
